spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: pages
          uri: https://dashaun-dev.github.io
          predicates:
            - Path=/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: https://auth.dashaun.dev
        registration:
          spring:
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            client-id: client
            client-secret: secret
            provider: spring
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user.read,openid