management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: root
          uri: https://dashaun-dev.github.io
          predicates:
            - Path=/**
  threads:
    virtual:
      enabled: true